# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2.1
jobs:
  build:
    working_directory: ~/aoc2020
    docker:
      - image: circleci/openjdk:14-jdk-buster
    environment:
      # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
      GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"
    steps:
      - checkout
      - run:
          name: Run junit tests
          command: ./gradlew test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
